from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from scripts.ai_sync import (
    SyncError,
    build_rendered_content,
    init_project,
    sync_project_templates,
    write_rendered_content,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
CURRENT_AI_STANDARDS_VERSION = "1.4.0"
CURRENT_RELEASE_DATE = "2026-04-20"
MANIFEST_RELEASE_BLOCK = (
    f'ai_standards_version = "{CURRENT_AI_STANDARDS_VERSION}"\n'
    f'project_version = "{CURRENT_AI_STANDARDS_VERSION}"\n'
    f'project_release_date = "{CURRENT_RELEASE_DATE}"\n'
)


def test_render_contains_expected_markers(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = [\n'
        '  "core/base",\n'
        '  "core/git-workflow",\n'
        '  "core/architecture",\n'
        '  "core/error-handling",\n'
        ']\n'
        'features = ["conport", "design-first-collaboration", "structured-artifacts"]\n'
        'stacks = ["python", "fastapi", "vue"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        'optional_local_overrides = ["docs/ai/private-rules.local.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )
    (project_root / "docs" / "ai" / "private-rules.local.md").write_text(
        "# Private AI Rules\n\n- Private local override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert (
        f"Generated by ai-standards v{CURRENT_AI_STANDARDS_VERSION} "
        f"release date: {CURRENT_RELEASE_DATE}"
    ) in result.content
    assert (
        f"Project version: {CURRENT_AI_STANDARDS_VERSION} "
        f"release date: {CURRENT_RELEASE_DATE}"
    ) in result.content
    assert f"<!-- Source: {REPO_ROOT}" not in result.content
    assert f"<!-- Project: {project_root}" not in result.content
    assert "## Design-First Collaboration" in result.content
    assert "## Lightweight Structured Artifacts" in result.content
    assert "## FastAPI Stack" in result.content
    assert "## Vue Stack" in result.content
    assert "Demo override." in result.content
    assert "Private local override." in result.content


def test_java_spring_stack_alias_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture", "core/error-handling"]\n'
        'features = ["conport"]\n'
        'stacks = ["java-spring"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Java Stack" in result.content
    assert "## Spring Stack" in result.content
    assert "## Spring Data JPA Stack" in result.content
    assert "Use constructor injection by default" in result.content


def test_explicit_java_spring_stack_combination_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture", "core/error-handling"]\n'
        'features = ["conport"]\n'
        'stacks = ["java", "spring", "spring-data-jpa"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "Use modern Java idioms supported by the repository baseline" in result.content
    assert (
        "Standardize REST error responses through centralized exception handling"
        in result.content
    )
    assert "Treat fetch plans deliberately" in result.content


def test_legacy_manifest_version_key_still_renders(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        'version = "0.1.0"\n'
        'project_version = "0.1.0"\n'
        'project_release_date = "2026-04-15"\n'
        'fragments = ["core/base"]\n'
        'features = ["conport"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert (
        f"Generated by ai-standards v{CURRENT_AI_STANDARDS_VERSION} "
        f"release date: {CURRENT_RELEASE_DATE}"
    ) in result.content
    assert "<!-- Requested ai-standards version: 0.1.0 -->" in result.content


def test_typescript_stack_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/error-handling"]\n'
        'features = ["conport"]\n'
        'stacks = ["typescript", "react"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## TypeScript Stack" in result.content
    assert "Use `satisfies` when you need to verify object shape" in result.content
    assert "## React Stack" in result.content
    assert (
        "Treat Effects as an escape hatch for synchronizing with external systems"
        in result.content
    )
    assert "When reading mutable state from outside React" in result.content


def test_vue_stack_renders_modern_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["typescript", "vue"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Vue Stack" in result.content
    assert "prefer `<script setup>` as the default authoring style" in result.content
    assert "Prefer `computed` for derived state" in result.content
    assert "return a plain object of refs by default" in result.content


def test_nextjs_stack_renders_framework_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["typescript", "react", "nextjs"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Next.js Stack" in result.content
    assert "Treat Server Components as the default rendering boundary" in result.content
    assert "Use Server Actions for form-style mutations" in result.content
    assert "Provide route-level `loading`, `error`, and `not-found` boundaries" in result.content


def test_tanstack_query_stack_can_be_rendered_with_react(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["typescript", "react", "tanstack-query"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## TanStack Query Stack" in result.content
    assert "Use TanStack Query for server-state synchronization" in result.content
    assert "Keep query keys stable, structured, and domain-meaningful" in result.content
    assert "After mutations, revalidate affected server state deliberately" in result.content


def test_nuxt_vite_and_fsd_stacks_can_be_rendered_together(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["typescript", "vue", "nuxt", "vite", "fsd"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Nuxt Stack" in result.content
    assert (
        "Prefer `useFetch` or `useAsyncData` for SSR-friendly page and layout data"
        in result.content
    )
    assert (
        "Configure rendering and caching behavior intentionally with route rules"
        in result.content
    )
    assert "## Vite Stack" in result.content
    assert (
        "Access browser-exposed environment variables through `import.meta.env`"
        in result.content
    )
    assert "Prefer dynamic imports, route-level splitting" in result.content
    assert "## Feature-Sliced Design Stack" in result.content
    assert "Expose a deliberate public API for each slice or shared segment" in result.content


def test_vue_query_alias_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["typescript", "vue-query"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Vue Stack" in result.content
    assert "## TanStack Query Stack" in result.content
    assert "Move reusable stateful logic into composables" in result.content
    assert "Keep query keys stable, structured, and domain-meaningful" in result.content


def test_python_stack_renders_unified_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "Use type hints for public and shared module boundaries" in result.content
    assert (
        "Use `match` for closed variants, tagged states, and structural patterns"
        in result.content
    )
    assert "## Python Stack" in result.content
    assert "Avoid `Any` as a convenience shortcut" in result.content
    assert "Prefer `pathlib.Path` over stringly-typed path handling" in result.content
    assert "Prefer logging for application and library diagnostics" in result.content


def test_django_and_fastapi_stacks_render_updated_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["django", "fastapi"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Django Stack" in result.content
    assert "Use transactions deliberately around multi-step writes" in result.content
    assert "Prefer Django's built-in protections and conventions" in result.content
    assert "## FastAPI Stack" in result.content
    assert "Use explicit response contracts via `response_model`" in result.content
    assert "Use `lifespan` for application startup and shutdown resources" in result.content
    assert "Raise `HTTPException` at the HTTP boundary" in result.content


def test_django_drf_stack_renders_softened_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["django-drf"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Django REST Framework" in result.content
    assert "Choose `APIView`, generic views, or viewsets" in result.content
    assert "Use `Serializer` or `ModelSerializer` deliberately" in result.content
    assert "Validate incoming data at the API boundary" in result.content


def test_django_service_layer_and_save_orchestration_render(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["django", "django-service-layer", "django-save-orchestration"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Layered Architecture" in result.content
    assert "## Backend Layered Architecture" in result.content
    assert "## Django Service Layer" in result.content
    assert "This fragment is an opt-in architectural style" in result.content
    assert "Place write operations (create, update, delete) in service functions" in result.content
    assert "## Django Save Orchestration" in result.content
    assert "perform_create()` and `perform_update()` may delegate" in result.content
    assert "schedule it with `transaction.on_commit`" in result.content


def test_frontend_layered_architecture_stack_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["react", "frontend-layered-architecture"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Frontend Layered Architecture" in result.content
    assert "Expose public APIs for architectural units" in result.content
    assert (
        "Keep framework bootstrap, routing setup, and environment wiring separate"
        in result.content
    )


def test_review_lenses_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Multi-Lens Review" in result.content
    assert (
        "Quality over Efficiency when safety, readability, or correctness is at risk."
        in result.content
    )


def test_reasoning_hygiene_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["reasoning-hygiene"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Reasoning Hygiene" in result.content
    assert (
        "Reject prompt tricks that rely on incentives, emotional pressure, or challenge language"
        in result.content
    )


def test_autonomy_boundaries_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["autonomy-boundaries"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Autonomy Boundaries" in result.content
    assert (
        "Stop when a new abstraction, architectural layer, public contract change,"
        in result.content
    )


def test_structured_artifacts_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["structured-artifacts"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Lightweight Structured Artifacts" in result.content
    assert (
        "Create `MODULE_CONTRACT.md` only for major, risky, shared, or "
        "architecturally non-obvious modules." in result.content
    )


def test_written_file_matches_rendered_content(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    (project_root / "ai.project.toml").write_text(
        (REPO_ROOT / "templates" / "project_manifest.toml").read_text(encoding="utf-8"),
        encoding="utf-8",
    )
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        (REPO_ROOT / "templates" / "project_rules.md").read_text(encoding="utf-8"),
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)
    write_rendered_content(result)

    assert result.output_path.read_text(encoding="utf-8") == result.content


def test_render_cli_accepts_default_output_name_with_typer_024_plus(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    (project_root / "ai.project.toml").write_text(
        (REPO_ROOT / "templates" / "project_manifest.toml").read_text(encoding="utf-8"),
        encoding="utf-8",
    )
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        (REPO_ROOT / "templates" / "project_rules.md").read_text(encoding="utf-8"),
        encoding="utf-8",
    )

    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "ai_sync.py"),
            "render",
            "--project-root",
            str(project_root),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    assert (project_root / "AGENTS.md").exists()


def test_init_project_seeds_current_ai_standards_version(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()

    init_project(project_root)

    manifest = (project_root / "ai.project.toml").read_text(encoding="utf-8")

    assert f'ai_standards_version = "{CURRENT_AI_STANDARDS_VERSION}"' in manifest
    assert 'project_version = "replace-me"' in manifest


def test_missing_optional_override_does_not_fail(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["conport"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        'optional_local_overrides = ["docs/ai/private-rules.local.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "Demo override." in result.content
    assert "private-rules.local" not in result.content


def test_sync_project_templates_creates_agent_adapters_from_manifest(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["codex", "cursor"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    results = sync_project_templates(project_root)

    assert [result.status for result in results] == ["created", "created"]
    codex_skill = project_root / ".codex/skills/review-lenses/simplify-review/SKILL.md"
    cursor_rule = project_root / ".cursor/rules/simplify-review.mdc"
    assert codex_skill.exists()
    assert cursor_rule.exists()
    assert "Managed by ai-standards template:" in codex_skill.read_text(encoding="utf-8")
    assert "Managed by ai-standards template:" in cursor_rule.read_text(encoding="utf-8")


def test_sync_project_templates_updates_plain_copied_template(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)
    (project_root / ".cursor/rules").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["cursor"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )
    raw_template = (
        REPO_ROOT / "templates" / "review-lenses" / "simplify-review.cursor.mdc"
    ).read_text(encoding="utf-8")
    destination = project_root / ".cursor/rules/simplify-review.mdc"
    destination.write_text(raw_template, encoding="utf-8")

    results = sync_project_templates(project_root)

    assert [result.status for result in results] == ["updated"]
    assert "Managed by ai-standards template:" in destination.read_text(encoding="utf-8")


def test_sync_project_templates_skips_unmanaged_local_changes(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)
    (project_root / ".cursor/rules").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["cursor"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )
    destination = project_root / ".cursor/rules/simplify-review.mdc"
    destination.write_text("# custom local rule\n", encoding="utf-8")

    results = sync_project_templates(project_root)

    assert [result.status for result in results] == ["skipped-unmanaged"]
    assert destination.read_text(encoding="utf-8") == "# custom local rule\n"


def test_unknown_agent_in_manifest_raises_sync_error(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["vscode"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    try:
        build_rendered_content(project_root)
    except SyncError as error:
        assert "Unknown agent" in str(error)
    else:
        raise AssertionError("Expected SyncError for unsupported agent")
