from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from scripts.ai_sync import (
    SyncError,
    build_rendered_content,
    sync_project_templates,
    write_rendered_content,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_RELEASE_BLOCK = (
    'ai_standards_version = "0.1.0"\n'
    'project_version = "0.1.0"\n'
    'project_release_date = "2026-04-15"\n'
)


def test_render_contains_expected_markers(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = [\n'
        '  "core/base",\n'
        '  "core/git-workflow",\n'
        '  "core/architecture",\n'
        '  "core/error-handling",\n'
        ']\n'
        'features = ["conport", "design-first-collaboration", "structured-artifacts"]\n'
        'stacks = ["python", "fastapi", "vue"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        'optional_local_overrides = ["docs/ai/private-rules.local.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )
    (project_root / "docs" / "ai" / "private-rules.local.md").write_text(
        "# Private AI Rules\n\n- Private local override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "Generated by ai-standards v0.1.0 release date: 2026-04-15" in result.content
    assert "Project version: 0.1.0 release date: 2026-04-15" in result.content
    assert "## Design-First Collaboration" in result.content
    assert "## Lightweight Structured Artifacts" in result.content
    assert "## FastAPI Stack" in result.content
    assert "## Vue Stack" in result.content
    assert "Demo override." in result.content
    assert "Private local override." in result.content


def test_java_spring_stack_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture", "core/error-handling"]\n'
        'features = ["conport"]\n'
        'stacks = ["java-spring"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Java Spring Stack" in result.content
    assert "Prefer constructor injection over field injection." in result.content


def test_legacy_manifest_version_key_still_renders(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        'version = "0.1.0"\n'
        'project_version = "0.1.0"\n'
        'project_release_date = "2026-04-15"\n'
        'fragments = ["core/base"]\n'
        'features = ["conport"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "Generated by ai-standards v0.1.0 release date: 2026-04-15" in result.content
    assert "Requested ai-standards version:" not in result.content


def test_typescript_stack_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/error-handling"]\n'
        'features = ["conport"]\n'
        'stacks = ["typescript", "react"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## TypeScript Stack" in result.content
    assert "Use `satisfies` when you need to verify object shape" in result.content
    assert "## React Stack" in result.content


def test_python_stack_renders_unified_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "Use type hints for public and shared module boundaries" in result.content
    assert (
        "Use `match` for closed variants, tagged states, and structural patterns"
        in result.content
    )
    assert "## Python Stack" in result.content
    assert "Avoid `Any` as a convenience shortcut" in result.content
    assert "Prefer `pathlib.Path` over stringly-typed path handling" in result.content
    assert "Prefer logging for application and library diagnostics" in result.content


def test_django_and_fastapi_stacks_render_updated_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["django", "fastapi"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Django Stack" in result.content
    assert "Use transactions deliberately around multi-step writes" in result.content
    assert "Prefer Django's built-in protections and conventions" in result.content
    assert "## FastAPI Stack" in result.content
    assert "Use explicit response contracts via `response_model`" in result.content
    assert "Use `lifespan` for application startup and shutdown resources" in result.content
    assert "Raise `HTTPException` at the HTTP boundary" in result.content


def test_django_drf_stack_renders_softened_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["django-drf"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Django REST Framework" in result.content
    assert "Choose `APIView`, generic views, or viewsets" in result.content
    assert "Use `Serializer` or `ModelSerializer` deliberately" in result.content
    assert "Validate incoming data at the API boundary" in result.content


def test_review_lenses_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Multi-Lens Review" in result.content
    assert (
        "Quality over Efficiency when safety, readability, or correctness is at risk."
        in result.content
    )


def test_reasoning_hygiene_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["reasoning-hygiene"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Reasoning Hygiene" in result.content
    assert (
        "Reject prompt tricks that rely on incentives, emotional pressure, or challenge language"
        in result.content
    )


def test_structured_artifacts_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["structured-artifacts"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Lightweight Structured Artifacts" in result.content
    assert (
        "Create `MODULE_CONTRACT.md` only for major, risky, shared, or "
        "architecturally non-obvious modules." in result.content
    )


def test_written_file_matches_rendered_content(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    (project_root / "ai.project.toml").write_text(
        (REPO_ROOT / "templates" / "project_manifest.toml").read_text(encoding="utf-8"),
        encoding="utf-8",
    )
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        (REPO_ROOT / "templates" / "project_rules.md").read_text(encoding="utf-8"),
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)
    write_rendered_content(result)

    assert result.output_path.read_text(encoding="utf-8") == result.content


def test_render_cli_accepts_default_output_name_with_typer_024_plus(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    (project_root / "ai.project.toml").write_text(
        (REPO_ROOT / "templates" / "project_manifest.toml").read_text(encoding="utf-8"),
        encoding="utf-8",
    )
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        (REPO_ROOT / "templates" / "project_rules.md").read_text(encoding="utf-8"),
        encoding="utf-8",
    )

    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "ai_sync.py"),
            "render",
            "--project-root",
            str(project_root),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    assert (project_root / "AGENTS.md").exists()


def test_missing_optional_override_does_not_fail(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["conport"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        'optional_local_overrides = ["docs/ai/private-rules.local.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "Demo override." in result.content
    assert "private-rules.local" not in result.content


def test_sync_project_templates_creates_agent_adapters_from_manifest(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["codex", "cursor"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    results = sync_project_templates(project_root)

    assert [result.status for result in results] == ["created", "created"]
    codex_skill = project_root / ".codex/skills/review-lenses/simplify-review/SKILL.md"
    cursor_rule = project_root / ".cursor/rules/simplify-review.mdc"
    assert codex_skill.exists()
    assert cursor_rule.exists()
    assert "Managed by ai-standards template:" in codex_skill.read_text(encoding="utf-8")
    assert "Managed by ai-standards template:" in cursor_rule.read_text(encoding="utf-8")


def test_sync_project_templates_updates_plain_copied_template(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)
    (project_root / ".cursor/rules").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["cursor"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )
    raw_template = (
        REPO_ROOT / "templates" / "review-lenses" / "simplify-review.cursor.mdc"
    ).read_text(encoding="utf-8")
    destination = project_root / ".cursor/rules/simplify-review.mdc"
    destination.write_text(raw_template, encoding="utf-8")

    results = sync_project_templates(project_root)

    assert [result.status for result in results] == ["updated"]
    assert "Managed by ai-standards template:" in destination.read_text(encoding="utf-8")


def test_sync_project_templates_skips_unmanaged_local_changes(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)
    (project_root / ".cursor/rules").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["cursor"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )
    destination = project_root / ".cursor/rules/simplify-review.mdc"
    destination.write_text("# custom local rule\n", encoding="utf-8")

    results = sync_project_templates(project_root)

    assert [result.status for result in results] == ["skipped-unmanaged"]
    assert destination.read_text(encoding="utf-8") == "# custom local rule\n"


def test_unknown_agent_in_manifest_raises_sync_error(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["vscode"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    try:
        build_rendered_content(project_root)
    except SyncError as error:
        assert "Unknown agent" in str(error)
    else:
        raise AssertionError("Expected SyncError for unsupported agent")
